# Generated by Django 6.0.6 on 2026-07-03 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_discussion', to=settings.AUTH_USER_MODEL, verbose_name='Именинник')),
            ],
            options={
                'verbose_name': 'Обсуждение подарка',
                'verbose_name_plural': 'Обсуждения подарков',
            },
        ),
        migrations.CreateModel(
            name='GiftMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gifts.giftdiscussion', verbose_name='Обсуждение')),
            ],
            options={
                'verbose_name': 'Сообщение в чате подарка',
                'verbose_name_plural': 'Сообщения в чатах подарков',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='Куплено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подарок из списка желаний',
                'verbose_name_plural': 'Списки желаний',
                'ordering': ['-created_at'],
            },
        ),
    ]
