# Generated by Django 6.0.6 on 2026-07-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принята')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
